-- ============================================================================
-- RAG Pipeline Database Schema
-- Text-Image Fused Content Units Architecture
-- ============================================================================

-- Documents table
CREATE TABLE IF NOT EXISTS documents (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    doc_id VARCHAR(255) UNIQUE NOT NULL,
    title VARCHAR(500) NOT NULL,
    file_path TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    domain VARCHAR(100),
    total_pages INTEGER,
    metadata JSONB DEFAULT '{}'::jsonb
);

CREATE INDEX idx_documents_doc_id ON documents(doc_id);
CREATE INDEX idx_documents_domain ON documents(domain);

-- Image Assets table
CREATE TABLE IF NOT EXISTS image_assets (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    document_id UUID NOT NULL REFERENCES documents(id) ON DELETE CASCADE,
    doc_id VARCHAR(255) NOT NULL,  -- Denormalized for quick access
    page_number INTEGER NOT NULL,
    bbox JSONB NOT NULL,  -- {x1, y1, x2, y2} in page coordinates
    image_path TEXT NOT NULL,  -- Path to cropped image file
    auto_caption TEXT,  -- Generated by vision model
    image_hash VARCHAR(64),  -- For deduplication
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    metadata JSONB DEFAULT '{}'::jsonb
);

CREATE INDEX idx_image_assets_document_id ON image_assets(document_id);
CREATE INDEX idx_image_assets_doc_id ON image_assets(doc_id);
CREATE INDEX idx_image_assets_page ON image_assets(doc_id, page_number);

-- Content Units table (the key entity - fused text+image)
CREATE TABLE IF NOT EXISTS content_units (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    document_id UUID NOT NULL REFERENCES documents(id) ON DELETE CASCADE,
    doc_id VARCHAR(255) NOT NULL,  -- Denormalized
    page_number INTEGER NOT NULL,
    section_title VARCHAR(500),
    section_path TEXT,  -- Hierarchical path like "Chapter 1 > Section 2"
    text TEXT NOT NULL,
    unit_type VARCHAR(50) NOT NULL CHECK (unit_type IN ('TEXT_ONLY', 'IMAGE_WITH_CONTEXT')),
    image_id UUID REFERENCES image_assets(id) ON DELETE SET NULL,
    token_count INTEGER,
    bbox JSONB,  -- Text bounding box if available
    tags TEXT[],  -- Array of tags: domain, machine_type, safety_level, etc.
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    metadata JSONB DEFAULT '{}'::jsonb
);

CREATE INDEX idx_content_units_document_id ON content_units(document_id);
CREATE INDEX idx_content_units_doc_id ON content_units(doc_id);
CREATE INDEX idx_content_units_image_id ON content_units(image_id);
CREATE INDEX idx_content_units_unit_type ON content_units(unit_type);
CREATE INDEX idx_content_units_tags ON content_units USING GIN(tags);
CREATE INDEX idx_content_units_page ON content_units(doc_id, page_number);

-- Helper view: Content units with image info
CREATE OR REPLACE VIEW content_units_with_images AS
SELECT 
    cu.id,
    cu.document_id,
    cu.doc_id,
    cu.page_number,
    cu.section_title,
    cu.section_path,
    cu.text,
    cu.unit_type,
    cu.image_id,
    cu.token_count,
    cu.bbox,
    cu.tags,
    cu.created_at,
    ia.image_path,
    ia.bbox AS image_bbox,
    ia.auto_caption,
    d.title AS document_title,
    d.file_path AS document_file_path
FROM content_units cu
LEFT JOIN image_assets ia ON cu.image_id = ia.id
JOIN documents d ON cu.document_id = d.id;

-- Function to get image by content unit
CREATE OR REPLACE FUNCTION get_image_for_unit(unit_uuid UUID)
RETURNS TABLE (
    image_id UUID,
    image_path TEXT,
    bbox JSONB,
    auto_caption TEXT,
    page_number INTEGER
) AS $$
BEGIN
    RETURN QUERY
    SELECT 
        ia.id,
        ia.image_path,
        ia.bbox,
        ia.auto_caption,
        ia.page_number
    FROM content_units cu
    JOIN image_assets ia ON cu.image_id = ia.id
    WHERE cu.id = unit_uuid;
END;
$$ LANGUAGE plpgsql;

-- Function to get PDF section info
CREATE OR REPLACE FUNCTION get_pdf_section(unit_uuid UUID)
RETURNS TABLE (
    doc_id VARCHAR,
    document_title VARCHAR,
    file_path TEXT,
    page_number INTEGER,
    section_title VARCHAR,
    section_path TEXT
) AS $$
BEGIN
    RETURN QUERY
    SELECT 
        cu.doc_id,
        d.title,
        d.file_path,
        cu.page_number,
        cu.section_title,
        cu.section_path
    FROM content_units cu
    JOIN documents d ON cu.document_id = d.id
    WHERE cu.id = unit_uuid;
END;
$$ LANGUAGE plpgsql;

